---
title: "CodeBook"
output: html_document
---

## Variables 

* subject_test - subject IDs for the test
* subject_train - subject IDs for the train
* x_test - values of the measurement in test
* x_train - values of the measurement in train
* y_test - activity ID in test
* y_train - activity ID in test
* activity_labels - The activity performed with related IDs
* features - What type of measurements were performed

## Summary 

* Merged the training and the test sets to create one data set.
* Extracted only the measurements on the mean and standard deviation for each measurement.
* Useed descriptive activity names to name the activities in the data set.
* Appropriately labeled the data set with descriptive variable names.
* Created an independent tidy data from the messy data set with the average of each variable for each activity and each subject.

## Other Info

Refer to the run_analysis.R script to understand the functioning of each code block from the comments.
The script and the Rmd files were written in RStudio running R version 3.6.3 (2020-02-29). 
For more information on the data, read the README.txt file from the data zip folder. 